export const API_CODE_FB_SUCCESS = 0; //成功
export const API_CODE_FB_FAIL = 1; //失败
export const API_CODE_FB_EXCEPTION = 2; //异常
export const API_CODE_FB_NOT_AUTHORIZED = 3; //未授权
export const API_CODE_FB_LOGIN_FAIL = 4; //登录失败
export const API_CODE_FB_PARAMETERS_ERROR = 5; //非法参数
export const API_CODE_FB_SYSTEM_ERROR = 6; //系统错误，请联系管理员
export const API_CODE_FB_NOT_FOUND = 7; //未找到相关数据
export const API_CODE_FB_SYSTEM_MAINTENANCE = 8; //系统维护中，维护时间[%s-%s]
export const API_CODE_FB_CHANNEL_USER_BALANCE_NOT_ENOUGH = 9; //三方用户余额不足
export const API_CODE_FB_DUPLICATE_DATA = 10; //数据重复
export const API_CODE_FB_FUNCTION_TEMPORARILY_UNAVAILABLE = 11; //功能临时不可用
export const API_CODE_FB_TOO_MANY_REQUESTS = 12; //请求太频繁
export const API_CODE_FB_NOT_FOUND_14002 = 14002; //Not found	未找到相关数据
export const API_CODE_FB_CALLING_REMOTE_SERVICE_RETURNS_BUSINESS_EXCEPTION = 14003; //Calling remote service returns business exception	服务器开小差了
export const API_CODE_FB_FORBID_RESUBMIT = 14004; //Forbid Resubmit	已提交，请稍后
export const API_CODE_FB_MERCHANT_DOES_NOT_EXIST_14005 = 14005; //Merchant does not exist!	商户不存在
export const API_CODE_FB_THE_SIGN_IS_INVALID = 14006; //The sign is invalid!	签名无效
export const API_CODE_FB_THE_CHANNEL_IS_INVALID = 14007; //The channel is invalid!	通道无效
export const API_CODE_FB_THE_REQUEST_HEADER_IS_INVALID = 14008; //The request header is invalid!	请求header无效
export const API_CODE_FB_NOT_LOGIN_PLEASE_LOGIN = 14009; //Not Login, please login!	账号未登录，请登录
export const API_CODE_FB_LOGIN_TIMEOUT_PLEASE_LOGIN_AGAIN = 14010; //Login timeout, please login again!	账号已登出，请重新登录
export const API_CODE_FB_PAGE_NOT_FOUND = 14013; //Page not found	页面未找到
export const API_CODE_FB_FILE_SIZE_GREATER_THAN = 14040; //File size greater than %s	文件大于 %s
export const API_CODE_FB_FILE_FORMAT_ERROR = 14041; //File format error	文件转换失败
export const API_CODE_FB_PLEASE_SELECT_PICTURE = 14042; //Please select picture	请选择图片
export const API_CODE_FB_FILE_UPLOAD_FAILED = 14043; //File upload failed	文件上传失败
export const API_CODE_FB_FILE_DELETE_FAILED = 14044; //File delete failed	文件删除失败
export const API_CODE_FB_TIME_PARAMETER_CANNOT_EXCEED_DAYS = 14051; //Time parameter cannot exceed %s days!	查询时间天数范围不合法
export const API_CODE_FB_TIME_SPAN_CANNOT_EXCEED_HOURS = 14052; //Time span cannot exceed %s hours!	查询时间范围不合法
export const API_CODE_FB_ACCOUNT_STATUS_DISABLED = 14057; //Account status disabled!	账户异常
export const API_CODE_FB_THE_MATCH_DO_NOT_SUPPORT_ALLUP = 14058; //The match do not support allUp!	赛事不支持串关投注
export const API_CODE_FB_THE_MARKET_OPTION_HAS_BEEN_UPDATED = 14059; //The market option has been updated!	玩法有更新
export const API_CODE_FB_THE_MERCHANT_DISABLE_RESERVE_BET = 14060; //The merchant disable reserve bet!	商户禁用预约投注
export const API_CODE_FB_THE_MERCHANT_DISABLE_SINGLE_RESERVE_CASH_OUT = 14061; //The merchant disable single reserve cash out!	商户禁用单关预约提前结算
export const API_CODE_FB_THE_MERCHANT_DISABLE_SINGLE_CASH_OUT = 14062; //The merchant disable single cash out!	商户禁用单关提前结算
export const API_CODE_FB_THE_MERCHANT_ONLY_ALLOW_CASH_OUT_ONCE = 14063; //The merchant only allow cash out once!	商户仅允许单次提前结算
export const API_CODE_FB_THE_MERCHANT_DISABLE_PARLAY_CASH_OUT = 14064; //The merchant disable parlay cash out!	商户禁用串关提前结算
export const API_CODE_FB_THE_MERCHANT_DISABLE_PARLAY_RESERVE_CASH_OUT = 14065; //The merchant disable parlay reserve cash out!	商户禁用串关预约提前结算
export const API_CODE_FB_CASHOUT_OF_PRINCIPAL_AMOUNT_ERROR = 14066; //CashOut of principal amount error	提前结算本金金额错误
export const API_CODE_FB_DATA_EXCEPTION = 14067; //data exception	数据异常
export const API_CODE_FB_BET_FREQUENTLY_PLEASE_WAIT = 14068; //Bet frequently, please wait!	投注过于频繁，请稍等！
export const API_CODE_FB_PLEASE_PROVIDE_MERCHANTID_AND_TIMESTAMP_IN_THE_HEADERS = 14069; //Please provide merchantId and timestamp in the headers	请在headers中提供merchantId和timestamp
export const API_CODE_FB_CURRENCY_ID_MUST_NOT_NULL_14070 = 14070; //Currency id must not null	币种id不能为空
export const API_CODE_FB_CALLBACK_URL_MUST_NOT_BLANK_WHERE_CHANNEL_IS_SEAMLESS_WALLET_14071 = 14071; //Callback url must not blank where channel is seamless wallet	渠道钱包类型为免转时，回调地址不能为空
export const API_CODE_FB_CHANNEL_CONFIGURATION_ERROR = 14072; //Channel configuration error	渠道配置错误
export const API_CODE_FB_WHEN_THE_CHANNEL_IS_NON_TRANSFER_FREE_NO_NEED_TO_PROVIDE_CALLBACK = 14073; //When the channel is non transfer free, there is no need to provide a callback address	渠道为非免转时，无需提供回调地址
export const API_CODE_FB_CHANNEL_CALLBACK_SERVICE_DISABLE = 14074; //Channel callback service disable	渠道服务不可用
export const API_CODE_FB_CURRENCY_TYPE_MUST_NOT_NULL_14075 = 14075; //Currency type must not null	币种类型不能为空
export const API_CODE_FB_CURRENCY_TYPE_IS_NOT_EXISTING = 14076; //Currency type is not existing	币种类型不存在
export const API_CODE_FB_LIST_OF_CURRENCY_ID_MUST_NOT_EMPTY = 14077; //List of currency id must not empty	币种id集合不能为空
export const API_CODE_FB_CURRENCY_NOT_SUPPORTED_BY_MERCHANT = 14078; //Currency not supported by merchant	币种不被商户支持
export const API_CODE_FB_SEAMLESS_WALLET_USERS_DO_NOT_SUPPORT_TRANSFER_OPERATIONS = 14079; //Seamless wallet users do not support transfer operations	免转钱包用户不支持转账操作
export const API_CODE_FB_PLEASE_ENTER_A_VALID_TRANSFER_CURRENCY = 14080; //Please enter a valid transfer currency	请输入有效的转账币种
export const API_CODE_FB_CURRENCY_IS_NOT_EXISTING = 14081; //Currency is not existing	币种不存在
export const API_CODE_FB_ORDER_IS_NOT_EXISTING_14082 = 14082; //Order is not existing	订单不存在
export const API_CODE_FB_FAILED_TO_GET_USER_BALANCE_14083 = 14083; //Failed to get user balance	获取用户余额失败
export const API_CODE_FB_MARKET_NOT_FOUND_14084 = 14084; //Market not found	盘口不存在
export const API_CODE_FB_RESERVE_BET_AMOUNT_EXCEEDS_THE_LIMIT_14085 = 14085; //Reserve bet amount exceeds the limit	预约投注额超过限制
export const API_CODE_FB_BATCH_EDIT_USER_ODDS_LEVEL_CANNOT_BE_GREATER = 14086; //Batch Edit user odds level cannot be greater than Channel Odds Level , Please contact FB Risk Team	批量修改用户赔率等级不能大于用户所属渠道的赔率等级，请联系FB风控人员
export const API_CODE_FB_SINGLE_CURRENCY_USERS_DO_NOT_NEED_TO_CREATE_A_WALLET = 14087; //Single currency users do not need to create a wallet	单币种用户无需创建钱包
export const API_CODE_FB_WRONG_ODDS_FORMAT_OF_RESERVATION_BETTING = 14088; //Wrong odds format of reservation betting	预约投注赔率类型错误
export const API_CODE_FB_WRONG_ODDS_FORMAT_OF_BETTING = 14089; //Wrong odds format of betting	投注赔率类型错误
export const API_CODE_FB_MAXIMUM_SELECTIONS_REACHED = 14090; //Maximum selections reached %d	超过最大选项数 %d
export const API_CODE_FB_TOURNAMENT_ID_INCORRECT = 14091; //tournament id incorrect	联赛ID错误
export const API_CODE_FB_THE_REQUEST_IP_ADDRESS_DOES_NOT_MATCH_THE_ALLOWED_WHITELIST = 14092; //The request IP address(%s) does not match the allowed whitelist	请求IP(%s)与白名单IP不一致
export const API_CODE_FB_BET_FAILED = 3000; //投注失败！
export const API_CODE_FB_BALANCE_NOT_ENOUGH = 3001; //余额不足！
export const API_CODE_FB_INVALID_MARKET = 3002; //盘口已关闭！
export const API_CODE_FB_ODDS_CHANGED = 3003; //赔率已变更！
export const API_CODE_FB_MAX_SELECTIONS_REACHED_3004 = 3004; //超过单次投注订单数！
export const API_CODE_FB_STAKE_BELOW_LOWER_LIMIT = 3005; //投注额小于最小限额！
export const API_CODE_FB_CUMULATIVE_STAKE_OF_PER_MATCH_REACHED = 3006; //单场总投注超过限额！
export const API_CODE_FB_CUMULATIVE_STAKE_OF_PER_DAY_REACHED = 3007; //单日总投注超过限额！
export const API_CODE_FB_MAX_STAKE_CHANGED = 3008; //最大投注额已更新！
export const API_CODE_FB_MAX_SELECTIONS_REACHED_PARLAY = 3009; //超过最大串关数！
export const API_CODE_FB_PARLAY_UNSUPPORTED = 3010; //包含不支持串关的选项！
export const API_CODE_FB_OPTIONS_SHOULD_COME_FROM_DIFFERENT_MATCH = 3011; //相同比赛不能串关！
export const API_CODE_FB_MAX_MATCHES_TIME_SPAN_REACHED = 3015; //开赛时间跨度超过最大值！
export const API_CODE_FB_MAX_SINGLE_MATCH_POSSIBLE_WIN_REACHED = 3016; //您已超过单场赛事最大可赢额！
export const API_CODE_FB_UNSUPPORTED_CURRENCY = 3017; //不支持的币种！
export const API_CODE_FB_ODDS_CHANGED_ADJUSTING = 3018; //赔率调整中！
export const API_CODE_FB_GET_BALANCE_FAILED = 3019; //获取三方余额失败！
export const API_CODE_FB_CUMULATIVE_STAKE_OF_PER_MARKET_REACHED = 3020; //单场玩法总投注超过限额！
export const API_CODE_FB_ODDS_TYPE_ERROR = 3021; //赔率类型有误！
export const API_CODE_FB_DIFFERENT_MATCH_TYPES_CANNOT_BE_COMBINED_INTO_A_PARLAY = 3026; //不同比赛类型不能串关！
export const API_CODE_FB_PLEASE_INPUT_USERNAME = 5000; //请输入用户名
export const API_CODE_FB_USERNAME_OR_PASSWORD_INCORRECT = 5001; //用户名或密码不正确
export const API_CODE_FB_PASSWORD_MODIFIED_SUCCESS = 5003; //密码修改成功
export const API_CODE_FB_LOGIN = 5004; //请登录
export const API_CODE_FB_LOGIN_EXCEPTION = 5005; //登录异常
export const API_CODE_FB_USER_ID = 5007; //请输入用户id
export const API_CODE_FB_ACCOUNT_ID = 5008; //请输入系统账号id
export const API_CODE_FB_NEW_PASSWORD_AND_RETYPE_PASSWORD_MUST_BE_CONSISTENT = 5009; //新密码和重输入密码必须保持一致
export const API_CODE_FB_OLD_PASSWORD_INCORRECT = 5010; //旧密码不正确
export const API_CODE_FB_USER_NAME_DUPLICATION = 5011; //用户名重复
export const API_CODE_FB_INTERFACE_EXCEPTION = 5012; //界面异常
export const API_CODE_FB_USER_NOT_ASSOCIATED_WITH_ANY_ROLE = 5014; //用户未关联任何角色
export const API_CODE_FB_ROLE_IDS_CANNOT_BE_EMPTY = 5015; //角色id列表不能为空
export const API_CODE_FB_USER_HAS_BEEN_DISABLED = 5017; //用户已禁用
export const API_CODE_FB_ROLE_HAS_BEEN_DISABLED = 5018; //角色已禁用
export const API_CODE_FB_BANNER_TYPE_INVALID = 5019; //banner类型无效
export const API_CODE_FB_IMAGE_URL_CANNOT_BE_EMPTY = 5020; //图片url不能为空
export const API_CODE_FB_LEAGUE_ID_CANNOT_BE_EMPTY = 5021; //联赛id不能为空
export const API_CODE_FB_MATCH_ID_CANNOT_BE_EMPTY = 5022; //赛事id不能为空
export const API_CODE_FB_MATCH_BEGIN_TIME_CANNOT_BE_EMPTY = 5023; //赛事开始时间不能为空
export const API_CODE_FB_PLAYING_TIME_CANNOT_BE_EMPTY = 5024; //播放时间不通为空
export const API_CODE_FB_SPORT_ID_CANNOT_BE_EMPTY = 5025; //运动各类不能为空
export const API_CODE_FB_START_PLAYING_TIME_MUST_BE_LESS_THAN_THE_END_PLAYING_TIME = 5026; //开始播放时间必须小于结束时间
export const API_CODE_FB_START_TIME_MUST_BE_LATER_THAN_THE_CURRENT_TIME = 5027; //开播时间必须大于等于当前时间
export const API_CODE_FB_BANNER_ALREADY_EXISTS = 5028; //此banner数据已存在
export const API_CODE_FB_NUMBER_OF_BANNERS_CANNOT_BE_MORE_THAN_10 = 5029; //banner条数不能超过10条
export const API_CODE_FB_ROLE_NAME_ALREADY_EXISTS = 5034; //角色名已存在
export const API_CODE_FB_MEMBER_ID_DOES_NOT_EXIST = 5035; //此会员不存在
export const API_CODE_FB_CHANNEL_DOES_NOT_EXIST = 5036; //渠道不存在
export const API_CODE_FB_MERCHANT_NOT_EXIST = 5038; //商户不存在
export const API_CODE_FB_MERCHANT_NAME_DUPLICATION = 5039; //商户名重复
export const API_CODE_FB_MERCHANT_USER_NOT_FOUND = 5040; //商户用户不存在
export const API_CODE_FB_MERCHANT_IS_DISABLE = 5041; //商户被禁用
export const API_CODE_FB_CONNECTOR_NOT_FOUND = 5042; //联系人不存在
export const API_CODE_FB_MAXIMUM_CHANNELS_REACHED = 5043; //渠道数量已达最大值，请联系管理员调整！
export const API_CODE_FB_CHANNEL_CODE_DUPLICATION = 5044; //渠道编码重复
export const API_CODE_FB_MAXIMUM_MERCHANTS_REACHED = 5045; //下级商户数量已达最大值，请联系管理员调整！
export const API_CODE_FB_MERCHANT_CODE_DUPLICATION = 5046; //商户编码重复
export const API_CODE_FB_LOGIN_IP_NOT_IN_WHITELIST = 5047; //ip不在白名单: %s
export const API_CODE_FB_CODE_OF_FIRST_LEVEL_MERCHANT_MUST_NOT_BE_NULL = 5048; //合伙商编号不能为空
export const API_CODE_FB_MAXIMUM_NUMBER_OF_SUB_MERCHANTS_CANNOT_BE_LESS_THAN_THE_NUMBER_OF_EXISTING_SUB_MERCHANTS = 5049; //子商户上限不能小于已有子商户数量
export const API_CODE_FB_MAXIMUM_NUMBER_OF_SUB_CHANNELS_CANNOT_BE_LESS_THAN_THE_NUMBER_OF_EXISTING_SUB_CHANNELS = 5050; //子渠道上限不能小于已有子渠道数量
export const API_CODE_FB_ORDER_ID_USER_ID_CHANNEL_ID_MUST_NOT_ALL_BE_NULL = 5051; //订单id、用户id、渠道id不能都为空
export const API_CODE_FB_DOWNLOAD_BETS_MORE_THAN_10000 = 5052; //下载订单超过一万条，请修改查询范围
export const API_CODE_FB_BEGIN_AND_END_TIME_SPAN_CANNOT_EXCEED_ONE_DAY = 5053; //起止时间跨度不能超过一天
export const API_CODE_FB_BEGIN_AND_END_TIME_SPAN_CANNOT_EXCEED_31_DAY = 5054; //起止时间跨度不能超过31天
export const API_CODE_FB_PLEASE_CONTACT_OUR_CUSTOMER_SERVICE_TO_MODIFY_USER_LIMIT = 5055; //请联系客服调整限额
export const API_CODE_FB_USER_LIMIT_CANNOT_BE_GREATER_THAN_THE_CHANNEL_LIMIT = 5056; //用户限额不能大于所属渠道限额
export const API_CODE_FB_USER_LIMIT_CANNOT_BE_GREATER_THAN_THE_FB_PRESET_USER_LIMIT = 5057; //用户限额不能大于FB预设的用户限额
export const API_CODE_FB_CHANNEL_USER_NOT_FOUND = 5058; //渠道用户不存在
export const API_CODE_FB_ID_NOT_FOUND = 5059; //ID不存在
export const API_CODE_FB_PLEASE_CONTACT_FB_RISK_CONTROL = 5060; //请联系FB风控
export const API_CODE_FB_LEAGUE_NOT_FOUND = 5061; //联赛不存在
export const API_CODE_FB_CHANNEL_LEAGUE_CONFIG_MORE_THAN_D = 5062; //渠道联赛配置数量超过%d
export const API_CODE_FB_PLEASE_ENTER_THE_DYNAMIC_VERIFICATION_CODE = 5063; //请输入动态验证码
export const API_CODE_FB_DYNAMIC_VERIFICATION_CODE_IS_INVALID = 5064; //动态验证码无效
export const API_CODE_FB_CHANNEL_NAME_EXISTS = 6000; //渠道名称已存在
export const API_CODE_FB_QUERY_TIME_IS_NULL = 6001; //查询时间为空
export const API_CODE_FB_PLATFORM_FEES_ARE_ILLEGAL = 6002; //平台费用是数据非法
export const API_CODE_FB_PLATFORM_FEES_TYPE_ARE_ILLEGAL = 6003; //平台收费类型是非法的
export const API_CODE_FB_ANNOUNCEMENT_DOES_NOT_EXIST = 6004; //公告不存在，请刷新页面
export const API_CODE_FB_DELETED_BULLETIN_CANNOT_BE_DELETED = 6005; //已删除的公告无法删除
export const API_CODE_FB_SCHEDULED_PUBLISH_TIME_MUST_BE_GREATER_THAN_THE_CURRENT_TIME = 6006; //计划发布时间必须大于当前时间
export const API_CODE_FB_ONLY_THE_UNPUBLISHED_BULLETIN_CAN_BE_EDITED = 6007; //只有未发表的公告才能编辑
export const API_CODE_FB_PLEASE_INPUT_END_TIME_TYPE = 6008; //请输入公告时间类型
export const API_CODE_FB_PLEASE_INPUT_TIME = 6009; //请输入时间
export const API_CODE_FB_STATEMENT_HAS_BEEN_SETTLED = 6010; //此数据已结算
export const API_CODE_FB_PLAYER_ANNOUNCEMENTS_ALREADY_EXIST = 6011; //玩家公告数据已存在
export const API_CODE_FB_UNSUPPORTED_SPORT_TYPES = 6012; //不支持的运动类型
export const API_CODE_FB_MERCHANT_SETTLEMENT_NOT_FOUND = 6013; //商户结算单不存在
export const API_CODE_FB_AGENT_SETTLEMENT_NOT_FOUND = 6014; //代理结算单不存在
export const API_CODE_FB_ILLEGAL_OPERATION_ON_CURRENT_AGENT_SETTLEMENT_STATUS = 6015; //此操作在当前代理结算单状态下非法
export const API_CODE_FB_CALLBACK_URL_MUST_NOT_BE_BLANK_WHERE_CHANNEL_IS_SEAMLESS_WALLET = 6016; //渠道钱包类型为免转时，回调地址不能为空
export const API_CODE_FB_BALANCE_MUST_NOT_BE_NULL = 6017; //余额不能为空
export const API_CODE_FB_NOT_ALLOW_TO_CHANGE_CREDIT_TYPE_WHEN_CREDIT_TYPE_OF_PARENT_AGENT_IS_CREDIT = 6018; //父商户授信，本商户不允许修改授信类型
export const API_CODE_FB_CAN_NOT_UPDATE_MERCHANT_BALANCE_WHEN_CREDIT_TYPE_IS_UNLIMITED = 6019; //当商户的授信类型为不限制时，不能修改余额
export const API_CODE_FB_BALANCE_IS_INSUFFICIENT = 6020; //余额不足
export const API_CODE_FB_AVAILABLE_CREDIT_BALANCE_FOR_MERCHANT_IS_INSUFFICIENT = 6021; //商户授信可用额度不足
export const API_CODE_FB_CREDIT_TYPE_OF_CHANNEL_MUST_NOT_SHARE_WHEN_CREDIT_TYPE_OF_PARENT_MERCHANT_IS_UNLIMITED = 6022; //父商户授信类型为不限时，渠道授信类型不能为共享
export const API_CODE_FB_CREDIT_TYPE_OF_CHANNEL_MUST_NOT_UNLIMITED_WHEN_CREDIT_TYPE_OF_PARENT_MERCHANT_IS_CREDIT = 6023; //父商户授信类型为授信时，渠道授信类型不能为不限制
export const API_CODE_FB_BALANCE_MUST_NOT_BE_ZERO = 6024; //余额不能为零
export const API_CODE_FB_CAN_NOT_UPDATE_CHANNEL_BALANCE_WHEN_CREDIT_TYPE_IS_NOT_FIX = 6025; //渠道授信类型为非固定时，不能修改余额
export const API_CODE_FB_CREDIT_TYPE_OF_FIRST_LEVEL_AGENT_MUST_NOT_BE_NULL = 6026; //合伙商授信类型不能为null
export const API_CODE_FB_CREDIT_TYPE_OF_MERCHANT_MUST_NOT_UNLIMITED_WHEN_CREDIT_TYPE_OF_PARENT_MERCHANT_IS_CREDIT = 6027; //父商户授信类型为授信时，商户授信类型不能为不限制
export const API_CODE_FB_CURRENCY_TYPE_MUST_NOT_BE_NULL_WHEN_NOT_SEAMLESS = 6028; //非免转商户币种类型不能为空
export const API_CODE_FB_CURRENCY_IDS_MUST_NOT_BE_NULL_WHEN_NOT_SEAMLESS = 6029; //非免转商户币种id集合不能为空
export const API_CODE_FB_CREDIT_TYPE_MUST_NOT_BE_NULL_WHEN_NOT_SEAMLESS = 6030; //非免转商户授信类型不能为空
export const API_CODE_FB_CURRENCY_ID_IS_NOT_IN_THE_VALID_CURRENCY_RANGE = 6031; //currencyId不在有效币种范围
export const API_CODE_FB_CURRENCY_ID_MUST_NOT_BE_NULL = 6032; //单币种商户currencyId不能为空
export const API_CODE_FB_TASK_IS_IN_PROCESS_AND_CANNOT_BE_CANCELLED = 6033; //任务正在处理中，不可取消
export const API_CODE_FB_TASK_STATUS_INVALID = 6034; //任务状态错误
export const API_CODE_FB_DOWNLOAD_TASK_ALREADY_EXISTED = 6035; //已有相同任务
export const API_CODE_FB_MIN_STAKE_AMOUNT_OF_SINGLE_CANNOT_BE_LOWER_THAN_THE_SYSTEM_SETTING = 6036; //单关最小投注额不可小于系统设置
export const API_CODE_FB_MIN_STAKE_AMOUNT_OF_PARLAY_CANNOT_BE_LOWER_THAN_THE_SYSTEM_SETTING = 6037; //串关最小投注额不可小于系统设置
export const API_CODE_FB_USER_LEVEL_NOT_FOUND = 6038; //用户等级不存在
export const API_CODE_FB_ACCOUNT_LOCKED = 6039; //用户被锁定
export const API_CODE_FB_ORDER_DOES_NOT_EXIST = 6040; //订单不存在！
export const API_CODE_FB_CASHOUT_ORDER_ALREADY_EXISTED = 6041; //提前结算订单已存在！
export const API_CODE_FB_ORDER_IS_NOT_CONFIRMED = 6042; //订单未确认！
export const API_CODE_FB_CASH_OUT_PAYOUT_CHANGED = 6043; //返还额已变更！
export const API_CODE_FB_SCORE_UPDATED = 6043; //比分已更新！
export const API_CODE_FB_ORDER_HAS_BEEN_REJECTED = 6044; //订单已拒单！
export const API_CODE_FB_ORDER_HAS_BEEN_CONFIRMED = 6045; //订单已接单！
export const API_CODE_FB_SOME_ORDERS_HAVE_BEEN_CONFIRMED_OR_REJECTED = 6046; //部分订单已接单/拒单！
export const API_CODE_FB_CASH_OUT_STAKE_IS_BELOW_THE_LOWER_LIMIT = 6047; //提前结算本金低于下限，请全部提前结算！
export const API_CODE_FB_LACK_OF_BALANCE = 6048; //余额不足！
export const API_CODE_FB_ODDS_HAS_CHANGED = 6049; //赔率已变更！
export const API_CODE_FB_INVALID_MARKET_6050 = 6050; //无效盘口！
export const API_CODE_FB_MAXIMUM_RESERVED_ORDER_REACHED = 6051; //预约订单数量超过上限！
export const API_CODE_FB_CANCEL_FAILED = 6052; //取消失败！
export const API_CODE_FB_RESERVED_STAKE_IS_BELOW_THE_LOWER_LIMIT = 6053; //预约金额小于最小金额！
export const API_CODE_FB_RESERVED_ORDER_DOES_NOT_EXIST = 6054; //预约单不存在！
export const API_CODE_FB_RESERVED_FAILED = 6055; //预约失败！
export const API_CODE_FB_RESERVE_BET_AMOUNT_EXCEEDS_THE_LIMIT = 6057; //预约投注额超过限制
export const API_CODE_FB_SCORE_CHANGED = 6058; //比分变化
export const API_CODE_FB_CANNOT_MODIFY_THE_STAKE_OF_PAID_RESERVATION = 6059; //不可修改已扣款预约单投注额
export const API_CODE_FB_RESERVED_ODDS_EXCEED_THE_MAXIMUM_ODDS_LIMIT = 6060; //预约赔率超过最高赔率限制！
export const API_CODE_FB_AUTHORIZATION_FAILURE = 6061; //授权失败
export const API_CODE_FB_ORDER_DOES_NOT_EXIST_17001 = 17001; //Order doesn't exist!	订单不存在
export const API_CODE_FB_RESERVED_CASHOUT_ORDER_ALREADY_EXISTED = 17002; //Reserved cashout order already existed!	预约提前结算订单已存在
export const API_CODE_FB_ORDER_IS_NOT_CONFIRMED_17003 = 17003; //Order isn't confirmed!	订单未确认
export const API_CODE_FB_CASHOUT_STAKE_EXCEED_STAKE_AMOUNT = 17004; //Cashout stake exceed stake amount!	提前结算本金大于投注额
export const API_CODE_FB_DONT_SUPPORT_CASHOUT = 17005; //Don't support cashout!	不支持提前结算
export const API_CODE_FB_MAXIMUM_RESERVED_CASHOUT_ORDER_REACHED = 17007; //Maximum reserved cashout order reached!	预约提前结算笔数已超过上限
export const API_CODE_FB_MAXIMUM_CASHOUT_TIMES_REACHED = 17008; //Maximum cashout times reached!	提前结算次数已超过上限
export const API_CODE_FB_CASHOUT_FAILED = 17009; //Cashout failed!	提前结算失败
export const API_CODE_FB_RESERVED_CASHOUT_RETURN_EXCEED_MAX_RETURN = 17010; //Reserved Cashout return exceed max return!	预约返还额超过订单返还额
export const API_CODE_FB_CASHOUT_STAKE_IS_BELOW_THE_LOWER_LIMIT_17011 = 17011; //Cashout stake is below the lower limit!	结算金额低于结算下限
export const API_CODE_FB_RESERVED_CASHOUT_ORDER_IS_PROCESSING = 17013; //Reserved cashout order is processing!	提前结算预约中
export const API_CODE_FB_RESERVED_CASHOUT_ORDER_DOES_NOT_EXIST = 17014; //Reserved cashout order doesn't exist!	提前结算预约单不存在
export const API_CODE_FB_NO_CASHOUT_RETURN = 17015; //NO Cashout return!	当前无报价
export const API_CODE_FB_NO_CASHOUT_RETURN_INVALID = 17016; //NO Cashout return!	当前概率无效
export const API_CODE_FB_RESERVE_CASHOUT_STAKE_IS_BELOW_THE_LOWER_LIMIT = 17017; //Reserve cashout stake is below the lower limit, please Cashout all stake!	預約提前结算本金低于下限，请全部提前结算！
