export const IM_CONTENT_TYPES = {
  TEXT: 101,
  CUSTOM: 110,
  QUOTE: 114,
  OA_NOTIFICATION: 1400,
} as const;

export const IM_SUPPORTED_CONTENT_TYPES = new Set<number>([
  IM_CONTENT_TYPES.TEXT,
  IM_CONTENT_TYPES.CUSTOM,
  IM_CONTENT_TYPES.QUOTE,
  IM_CONTENT_TYPES.OA_NOTIFICATION,
]);
